[project]
name = "fastMatMR"
version = "0.1.0"
description = "Add a short description here"
authors = ["Rohit Goswami <rog32@hi.is>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[tasks]

[dependencies]
r-renv = "1.0.2.*"
compilers = "1.6.0.*"
radian = "0.6.7.*"
