name: ROpenSci pkg-check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: pkgcheck
        uses: ropensci-review-tools/pkgcheck-action@v1.0.0
